### ISSUE TITLE
logcheck on multiple bands

### ISSUE THREAD

**Issue by gobris** [ciorceri/logXchecker#4]
Hello,
N1mm also exports as single file multiple band format.

On this case, it throws an error of 

Header errors :
Line 116 : PCall field is present multiple times
Line 117 : PWWLo field is present multiple times
Line 122 : PBand field is present multiple times
Line 121 : PSect field is present multiple times
Line 115 : TDate field is present multiple times
Line 124 : RName is present multiple times

And as a second problem,
it gives warning for every empty line as (tried to csplit the file to multiple files to eliminate the first problem) 

QSO errors :
Line 52 :  <- Qso line is too short
Line 53 :  <- Qso line is too short

attaching an example rules set + contest log

[examplelog.zip](https://github.com/ciorceri/logXchecker/files/4881250/examplelog.zip)

**Comment by ciorceri** [comment]
Hi Ozzy.

Related with 'field is present multiple times error', I can see that you have concatenated the 50,144 and 432 bands logs in a single file.
The EDI file format states that each log per band should be in individual file.
I did the split of the log in 3 different files:

> $ python3 logXchecker.py  -slc ./GOBRIS/1_50mhz.edi -r ./GOBRIS/rules_config.txt
logXchecker - v1.3
Checking log : ./GOBRIS/1_50mhz.edi
No error found

> $ python3 logXchecker.py  -slc ./GOBRIS/2_144mhz.edi -r ./GOBRIS/rules_config.txt
logXchecker - v1.3
Checking log : ./GOBRIS/2_144mhz.edi
No error found

> $ python3 logXchecker.py  -slc ./GOBRIS/3_432mhz.edi -r ./GOBRIS/rules_config.txt
logXchecker - v1.3
Checking log : ./GOBRIS/3_432mhz.edi
No error found

As you can see the logs are good and pass the checks.

Related with:
> Line 52 : <- Qso line is too short

In the QSOs part of the log you probably have left some empty lines. I will throw that error or all QSO lines that have less than 40 characters. You can ignore those errors if this is your case (empty lines).

Thanks and 73
